import numpy as np

AODC0 = 0.14  # Default value for aerosol optical depth
AODRETURN = 30.0  # Default value for AOD return time (minutes)
CCNCLEAN = max(5.0, (AODC0 / 0.0027) ** (1 / 0.640))
FLUXTUNE = 1.5  # Flux tuning parameter
TCRIT = 258.0
TF = 258.16
TCR = 273.16  # Critical temperature for cloud water/ice conversion
TCRF = 1.0 / (TCR - TF)  # Scaling factor for temperature conversion
G = 9.81 # Gravitational acceleration (m/s^2)
CP = 1004.0  # Specific heat of dry air at constant pressure (J/(kg*K))
XLV = 2.50e6  # Latent heat of vaporization (J/kg)
R_V = 461.0  # Specific gas constant for water vapor (J / kg / K)
ZKBMAX = 3000.0  # Maximum height for the boundary layer (m)
TINY = np.finfo(float).tiny
ORDER_AVER = 3  # Order of averaging for cloud base properties
L_MID = 300.0  # Mid-level length scale for inversion layer detection (m)
L_SHAL = 100.0  # Shallow length scale for inversion layer detection (m)
ZUSTART = 0.1
BETA_SH = 2.2
G_BETA_SH = 0.8974707
BETA_MID = 1.3
BETA_DD = 4.0
G_BETA_DD = 6.0
C0_SHAL = 0.001  # Parameter for shallow convection
MBDT = 0.5  # Mass balance delta time (s)
USE_EXCESS = 0  # Flag for shallow and mid convection tuning
DX_THRESH = 6500.0 # Threshold for grid spacing (meters)
FRH_THRESH = 0.9  # Maximum allowed fractional coverage
