name: MacOS GNU
# triggered events (push, pull_request) for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  macos_Build:
    name: Mac OS GNU Build
    # The type of runner that the job will run on
    runs-on: macos-latest

    env:
      # Work around bug in OpenMPI: See https://github.com/open-mpi/ompi/issues/6518
      OMPI_MCA_btl: "self,tcp"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install OpenMPI
      - name: Install OpenMPI
        run: brew install open-mpi

      # Test debug mode 
      - name: Test gf Debug 
        run: |
          cd ref
          rm -rf build
          mkdir build
          cd build
          #export OMP_NUM_THREADS=4
          export CC=gcc-11
          export FC=gfortran-11          
          cmake -DCMAKE_BUILD_TYPE=debug -DENABLE_GPU=off .. 
          make VERBOSE=1
          ctest --output-on-failure
          
      # Test release mode 
      - name: Test gf Release
        run: |
          cd ref
          rm -rf build
          mkdir build
          cd build
          #export OMP_NUM_THREADS=4
          export CC=gcc-11
          export FC=gfortran-11           
          cmake -DCMAKE_BUILD_TYPE=release -DENABLE_GPU=off ..
          make VERBOSE=1
          ctest --output-on-failure
